#################################
#  EagleVision 洞察鹰眼 Ver1.0  #
#################################
#请勿使用Reload重启 尽量Restart/Stop

#能标记多少格远的生物
tag range: 20

#实体被标记后能发光多长时间（单位秒）/ 9999以上为永久标记
glowing time: 30

#能透过什么方块标记实体（默认：草、蔓藤、叶子）
ignored block:
    - LONG_GRASS
    - DOUBLE_PLANT
    - VINE
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - ACACIA_LEAVES
    - BIRCH_LEAVES
    - DARK_OAK_LEAVES
    - JUNGLE_LEAVES