name: SAOLoad
main: com.SAOPJ.EquipmentLoad.Main
version: 1.0
author: DoloSaber
commands:
  FUZHONG:
    description: 查看当前负重值/开启debug模式！
    usage: /fuzhong [debug]
    aliases: fz
    permission: Load.useFUZHONG
    permission-message: §c无权执行！
permissions:
  Load.useFUZHONG:
    default: op