name: EagleVision
main: com.Dolo.EagleVision.Main
version: 1.0
author: DoloC8
depend: [ProtocolLib]
commands:
  EagleVision:
    description: 开启鹰眼！
    usage: /EagleVision 
    aliases: ev
    permission: ev.useEagleVision
    permission-message: §c无权执行！
permissions:
  ev.useEagleVision:
    default: op